var typer = new Typewriter('#typewriter')
//Font will be load only after first char shows
typer.typeString('中')
    .deleteAll()
    .typeString('loading fonts')
    .pauseFor(1000)
    .typeString('.')
    .pauseFor(2000)
    .typeString('.')
    .pauseFor(3000)
    .typeString('.')
    .pauseFor(4000)
    .typeString('.')
    .deleteAll()
    .typeString('Our Story Begins')
    .pauseFor(4000)
    .deleteAll()
    .typeString('二零一零年 夏')
    .pauseFor(2000)
    .deleteAll()
    .start()